---

- hosts: all
  become: true
  tasks:

  - name: install updates (ubuntu)
    apt:
      update: dist
      update_cache: yes
    when: ansible_distribution == "ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for ubuntu server
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest

