---

- hosts: all
  become: true
  tasks:

  - name: install updates (ubuntu)
    tags: always
    apt:
      update: dist
      update_cache: yes
    when: ansible_distribution == "ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for ubuntu server
    tags: apache2, apache, ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "ubuntu"

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
     

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (ubuntu)
    tags: db, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

