Vagrant.configure("2") do |config|

  SERVER_COUNT = 3
  SERVER_BOX = "ubuntu/jammy64"
  SERVER_USERNAME = `whoami` 
  SERVER_HOSTNAME_PREFIX = "vm-ubuntu-"
  SERVER_IP_PREFIX = "192.168.56."

  (1..SERVER_COUNT).each do |i|
    config.vm.define "server#{i}" do |server|
      server.vm.box = SERVER_BOX 
      server.vm.hostname = "#{SERVER_HOSTNAME_PREFIX}#{i}" 
#      server.ssh.username = SERVER_USERNAME
      server.vm.network "private_network", ip: "#{SERVER_IP_PREFIX}#{i+10}"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
    end
  end
end
