Vagrant.configure("2") do |config|

  SERVER_COUNT = 1
  SERVER_BOX = "ubuntu/jammy64"
  SERVER_USERNAME = "cjung-mo"
  SERVER_USER_PASSWORD = "cjung-mo"
  SERVER_HOSTNAME_PREFIX = "vm-ubuntu-"
  SERVER_IP_PREFIX = "192.168.56."

  (1..SERVER_COUNT).each do |i|
    config.vm.define "server#{i}" do |server|
      server.vm.box = SERVER_BOX 
      server.vm.hostname = "#{SERVER_HOSTNAME_PREFIX}#{i}" 
      server.vm.network "private_network", ip: "#{SERVER_IP_PREFIX}#{i+10}"
	  server.vm.network "forwarded_port", guest: 80, host: "800#{i}"
	  server.vm.network "forwarded_port", guest: 443, host: "808#{i}"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = 12
	  end
	  server.vm.provision "shell", inline: <<-SHELL
	  # check if the new user already exists.
	  if id -u #{SERVER_USERNAME} > /dev/null 2>&1; then
		  echo "User #{SERVER_USERNAME} already exists."
	  else
		  sudo useradd -m -s /bin/bash -p $(echo #{SERVER_USERNAME}| openssl passwd -1 -stdin) #{SERVER_USER_PASSWORD}
		  sudo usermod -aG sudo #{SERVER_USERNAME}
		  echo "User #{SERVER_USERNAME} created."
	  fi
	  SHELL
    end
  end
end
